service: sou-homepage-related

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment: ${file(./env.yml)}
  deploymentBucket:
    name: sumofus.org.serverless.us-east-1
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    -  Effect: "Allow"
       Action: "s3:*"
       Resource:
         - "arn:aws:s3:::sou-homepage-counter/*"
functions:
  check:
    handler: functions/check_email.handler
    events:
      - http:
          path: member
          method: get
          cors: true
  updateCount:
    handler: functions/count.handler
    events:
      - schedule: rate(1 hour)
  deploy:
    handler: functions/prismic.handler
    events:
      - http:
          path: prismic/webhook
          method: post
